{% set name = "data-morph-ai" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 23b22a133b8fdf673ed47321dc74d8cfa4ea78178bb0dcd8169eeb7ce7583490

build:
  entry_points:
    - data-morph = data_morph.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.3
    - numpy >=1.20
    - pandas >=1.2
    - pytweening >=1.0.5
    - scipy >=1.10.0
    - tqdm >=4.64.1

test:
  imports:
    - data_morph
  commands:
    - pip check
    - data-morph --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Teaching tool on the importance of data visualization.
  home: https://stefmolin.github.io/data-morph
  dev_url: https://github.com/stefmolin/data-morph
  doc_url: https://stefmolin.github.io/data-morph
  license: MIT
  license_file: LICENSE
  description: |
    Data Morph transforms an input dataset of 2D points into select shapes,
    while preserving the summary statistics to a given number of decimal points
    through simulated annealing.

extra:
  recipe-maintainers:
    - stefmolin
