{% set name = "data-morph-ai" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0e45cde340b3b299d75e3d3a2f22915a25b90b5492701101f4d791fc2e60b197

build:
  entry_points:
    - data-morph = data_morph.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.3
    - numpy >=1.20
    - pandas >=1.2
    - rich >=13.9.4

test:
  imports:
    - data_morph
  commands:
    - pip check
    - data-morph --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Teaching tool on the importance of data visualization.
  home: https://stefaniemolin.com/data-morph
  dev_url: https://github.com/stefmolin/data-morph
  doc_url: https://stefaniemolin.com/data-morph
  license: MIT
  license_file: LICENSE
  description: |
    Data Morph transforms an input dataset of 2D points into select shapes,
    while preserving the summary statistics to a given number of decimal
    points through simulated annealing. It is intended to be used as a
    teaching tool to illustrate the importance of data visualization.

extra:
  recipe-maintainers:
    - stefmolin
