{% set name = "data-morph-ai" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/data-morph-ai-{{ version }}.tar.gz
  sha256: cfa23d793d3c6f9f1772670b763051950a7ab4e0c0fd346fbc2c8c69db3960fc

build:
  entry_points:
    - data-morph = data_morph.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - matplotlib-base >=3.3
    - numpy >=1.20
    - pandas >=1.2
    - pytweening >=1.0.3
    - scipy >=1.10.0
    - tqdm >=4.64.1

test:
  imports:
    - data_morph
  commands:
    - pip check
    - data-morph --help
  requires:
    - pip

about:
  summary: Teaching tool on the importance of data visualization.
  home: https://stefmolin.github.io/data-morph
  dev_url: https://github.com/stefmolin/data-morph
  doc_url: https://stefmolin.github.io/data-morph
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stefmolin
